[workspace]
members = ["leptos-mview-core", "leptos-mview-macro"]

[workspace.package]
version = "0.4.4"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/blorbb/leptos-mview"

[package]
name = "leptos-mview"
keywords = ["macro", "leptos", "view"]
description = "A concise view macro for Leptos"
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[workspace.dependencies]
syn = "2"
quote = "1"
proc-macro2 = "1"
proc-macro-error2 = "2"

# dev dependencies #
trybuild = "1"
# needs to use ssr for some view-to-HTML features to work.
leptos = { version = "0.8.2", features = ["ssr"] }
leptos_router = { version = "0.8.2", features = ["ssr"] }
any_spawner = "0.3.0"

[dependencies] # tests with async components
leptos-mview-macro = { path = "leptos-mview-macro", version = "0.4.4" }

[dev-dependencies]
trybuild.workspace = true
leptos.workspace = true
leptos_router.workspace = true
any_spawner.workspace = true
leptos-mview = { path = ".", features = [] }

[features]
nightly = ["leptos-mview-macro/nightly"]

# https://github.com/blorbb/leptos-mview/issues/20
[target.'cfg(erase_components)'.dependencies]
leptos-mview-macro = { path = "leptos-mview-macro", version = "0.4.4", features = [
    "__internal_erase_components",
] }
