# Enable these when testing rust-analyzer etc with erase components.

[target.x86_64-unknown-linux-gnu]
rustflags = ["--cfg", "erase_components"]

[target.wasm32-unknown-unknown]
rustflags = ["--cfg", "erase_components"]
